//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThumbGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThumbGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/diskdrive.png.
        /// </summary>
        internal static string Drive_Image_Path {
            get {
                return ResourceManager.GetString("Drive_Image_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not store covers/backdrops links.
        /// </summary>
        internal static string ExportBackdropTypes_DoNotExportImages {
            get {
                return ResourceManager.GetString("ExportBackdropTypes_DoNotExportImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store links to moviesheets (the current settings for moviesheets will be used).
        /// </summary>
        internal static string ExportBackdropTypes_UseGeneratedMoviesheets {
            get {
                return ResourceManager.GetString("ExportBackdropTypes_UseGeneratedMoviesheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store internet links.
        /// </summary>
        internal static string ExportBackdropTypes_UseInternetLinks {
            get {
                return ResourceManager.GetString("ExportBackdropTypes_UseInternetLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store links to local images files (the &lt;Export Images&gt; settings will be used).
        /// </summary>
        internal static string ExportBackdropTypes_UseLocalExportedImages {
            get {
                return ResourceManager.GetString("ExportBackdropTypes_UseLocalExportedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/file.png.
        /// </summary>
        internal static string File_Image_Path {
            get {
                return ResourceManager.GetString("File_Image_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/folder.png.
        /// </summary>
        internal static string Folder_Image_Path {
            get {
                return ResourceManager.GetString("Folder_Image_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Computer.
        /// </summary>
        internal static string My_Computer_String {
            get {
                return ResourceManager.GetString("My_Computer_String", resourceCulture);
            }
        }
    }
}
